version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.13
  - dependency-name: "@types/node"
    versions:
    - 14.14.32
    - 14.14.37
  - dependency-name: next
    versions:
    - 10.0.8
    - 10.1.1
  - dependency-name: next-plugin-preact
    versions:
    - 3.0.4
  - dependency-name: "@next/bundle-analyzer"
    versions:
    - 10.0.8
  - dependency-name: preact-render-to-string
    versions:
    - 5.1.14
  - dependency-name: typescript
    versions:
    - 4.1.4
  - dependency-name: ini
    versions:
    - 1.3.8
