# To use this, acquire a deploy hook in pages first
name: Pages Hook Cron

on:
  schedule:
    - cron: '0 0 * * *'  # on 0:00 every day
  workflow_dispatch:
    {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Trigger Cloudflare Pages Deploy Hook
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Trigger hook
        uses: wei/curl@master
        with:
          args: -XPOST ${{secret.PAGES_DEPLOYHOOK}}